[package]
name = "snake_game"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
rand = "0.8"
once_cell = "1.19"

[build-dependencies]
winres = "0.1"

[[bin]]
name = "snake_game"
path = "src/main.rs"
windows-subsystem = "windows"